name: Vue Shop Deploy

on:
  push:
    branches:
      - dev
    
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Setup node_modules
        run: |
          npm install
          
      - name: Build
        run: |
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
          ssh-key: ${{ secrets.VUE_SHOP_DEPLOY_KEY }}